##https://github.com/actions/upload-artifact
##Every job gets their own runner machine, no two jobs runs on same a=machine
name: Deploy website
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Test code
        run: npm run test
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Build website
        run: npm run build
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4 ## Upload the build artifacts
        with: ## Specify the path to the build directory, additional configuration
          name: build ## name for retriving the artifacts, can also use multiple names
          path: |
            dist 
            pakage.json
          ## path/output/bin/  ## include and save the files here
          ## path/output/test-results put the result artifacts here
          ## !path/**/*.tmp ## Exclude any template files
  ## even theough teh artifacts are gathered in the build job, they are not available in the deploy job, because both jobs run on different machines
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4 ## Download the artifacts from previous job
        with:
          name: build ## Name of the artifact to download must be same as the one uploaded in abve job
      - name: Output file-lists
        run: ls -R
      - name: Deploy
        run: echo "Deploying..."
